[package]
name = "little-lookup"
version = "0.1.0"
authors = ["jscheel42 <jscheel42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.2", features = [ "mysql", "postgres", "sqlite" ] }
diesel_migrations = "1.4.0"
dotenv = "0.14.1"

[dependencies.rocket]
version = "0.4.2"
