[package]
name = "little-lookup"
version = "2.2.0"
authors = ["jscheel42 <jscheel42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "*" # dep in actix-web, added here so we can reference the crate in main.rs
actix-web = "3.3.3"
chrono = "0.4" # { version = "0.4", features = ["serde", "rustc-serialize"] }
diesel = { version = "1.4.8", features = [ "r2d2", "postgres", "chrono" ] }
diesel_migrations = "1.4.0"
dotenv = "0.15"
openssl = "*" # Needed for postgres
openssl-probe = "0.1.2"
tokio = "1.8.4"