[package]
name = "little-lookup"
version = "0.1.0"
authors = ["jscheel42 <jscheel42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9"
actix-rt = "1.1"
actix-web = "2.0"
diesel = { version = "1.4", features = [ "r2d2", "postgres" ] }
diesel_migrations = "1.4.0"
dotenv = "0.15"
futures = "0.3"
openssl = "*" # Needed for postgres
openssl-probe = "0.1.2"
