[package]
name = "little-lookup"
version = "2.5.0"
authors = ["jscheel42 <jscheel42@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "*" # dep in actix-web, added here so we can reference the crate in main.rs
actix-web = "4.5.1"
chrono = "0.4.33" # { version = "0.4", features = ["serde", "rustc-serialize"] }
diesel = { version = "2.1.4", features = [ "r2d2", "postgres", "chrono" ] }
diesel_migrations = "2.1.0"
dotenv = "0.15"
env_logger = "0.11.1"
log = "0.4.20"
openssl = "*" # Needed for postgres
openssl-probe = "0.1.5"
