# steps based on https://gist.github.com/jamesproud/4022da405709a633ba7f021a36d7b462

## BUILD IMAGE
FROM rust:latest as cargo-build

WORKDIR /usr/local/src

ADD . ./

RUN apt-get update
RUN apt-get install -y \
        libsqlite-dev \
        libsqlite3-dev \
        sqlite \
        sqlite3
RUN cargo build --release


## FINAL IMAGE
FROM frolvlad/alpine-glibc:latest

RUN addgroup -g 1000 app
RUN adduser -D -s /bin/sh -u 1000 -G app app
RUN mkdir /data
RUN chown app:app /data

ENV LITTLE_LOOKUP_DATABASE /data/default.db

WORKDIR /home/app

COPY --from=cargo-build /usr/local/src/target/release/little-lookup .
RUN chown app:app -R /home/app
USER app

EXPOSE 8088

RUN ls -lha /home/app/little-lookup

ENTRYPOINT ["/home/app/little-lookup"]
