services:
  little-lookup:
    # image: jscheel42/little-lookup:v2.2.0
    build: .
    environment:
      # - LITTLE_LOOKUP_PSK_READ=read
      - LITTLE_LOOKUP_PSK_WRITE=write
      - LITTLE_LOOKUP_DATABASE=postgres://docker:docker@postgres:5432/little-lookup
    ports: 
      - 8088:8088
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=little-lookup
    ports: 
      - 5432:5432